### ISSUE TITLE
inappropriate ioctl for device

### ISSUE THREAD

**Issue by cromoto** [renkasiyas/btb-grafana-dashboard#1]
Hi,
I've this issue 

```
Pulling btb_grafana (grafana/grafana:latest)...
latest: Pulling from grafana/grafana
97518928ae5f: Pull complete
5b58818b7f48: Extracting [==================================================>]     173B/173B
d9a64d9fd162: Download complete
4e368e1b924c: Download complete
867f7fdd92d9: Download complete
387c55415012: Download complete
07f94c8f51cd: Download complete
ce8cf00ff6aa: Download complete
e44858b5f948: Download complete
4000fdbdd2a3: Download complete
ERROR: failed to register layer: Failed to create btrfs snapshot: inappropriate ioctl for device
```

Running in ubuntu on a Synology docker.

**Comment by renkasiyas** [comment]
I'm not familiar with Synology, but quick search seems to be a thing with BTRFS and/or Synology and their interaction with Docker. https://www.reddit.com/r/docker/comments/mba2c7/how_do_i_make_docker_work_nicely_with_btrfs_host/

Let me know if I can help further.

**Comment by cromoto** [comment]
I think the problem is rather that the ubuntu image created by synology docker is also in BTRFS format. Maybe I should have done it in EXT4.

**Comment by cromoto** [comment]
I abandoned docker, I installed grafana and import your json. It works like that perfectly. Thank you for your work.

**Comment by renkasiyas** [comment]
> I abandoned docker, I installed grafana and import your json. It works like that perfectly. Thank you for your work.

That's another way to do it! Glad to hear that. Thank you for trying.
